"""
Image Extractor Service
Uses PyMuPDF (fitz) to extract images from PDF pages, then captions them
using Gemini Vision so they can be stored as searchable text in Pinecone.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
import base64
import io

try:
    import fitz  # PyMuPDF
    PYMUPDF_AVAILABLE = True
except ImportError:
    PYMUPDF_AVAILABLE = False
    print("[WARN] PyMuPDF not installed. Image extraction disabled. Run: pip install pymupdf")


@dataclass
class ExtractedImage:
    """Represents an image extracted from a PDF page."""
    page_number: int
    image_index: int          # Index of the image on the page (0-based)
    image_bytes: bytes        # Raw PNG/JPEG bytes
    width: int
    height: int
    caption: str = ""         # Generated by Gemini Vision (filled later)
    metadata: Dict[str, Any] = field(default_factory=dict)


# Minimum pixel area to filter out logos/decorations
_MIN_IMAGE_AREA = 5000  # 100×50 px or similar


def extract_images_from_pdf(pdf_path: str) -> List[ExtractedImage]:
    """
    Extract images from each page of a PDF using PyMuPDF.

    Only images above a minimum size threshold are returned to avoid
    extracting tiny icons and decorations.

    Args:
        pdf_path: Path to the PDF file.

    Returns:
        List of ExtractedImage objects (one per meaningful image found).
    """
    if not PYMUPDF_AVAILABLE:
        return []

    extracted: List[ExtractedImage] = []

    try:
        doc = fitz.open(pdf_path)
        for page_num in range(len(doc)):
            page = doc[page_num]
            image_list = page.get_images(full=True)

            for img_idx, img_info in enumerate(image_list):
                xref = img_info[0]
                try:
                    base_image = doc.extract_image(xref)
                    img_bytes = base_image["image"]
                    width = base_image.get("width", 0)
                    height = base_image.get("height", 0)

                    # Skip tiny images (icons, bullets, etc.)
                    if width * height < _MIN_IMAGE_AREA:
                        continue

                    extracted.append(ExtractedImage(
                        page_number=page_num + 1,  # 1-based
                        image_index=img_idx,
                        image_bytes=img_bytes,
                        width=width,
                        height=height,
                        metadata={
                            "ext": base_image.get("ext", "png"),
                            "colorspace": base_image.get("colorspace", ""),
                        }
                    ))
                except Exception as e:
                    print(f"[WARN] Could not extract image {img_idx} on page {page_num + 1}: {e}")
                    continue

        doc.close()

    except Exception as e:
        print(f"[ERROR] Image extraction error: {e}")

    print(f"[INFO] Extracted {len(extracted)} images from PDF")
    return extracted


def caption_images_with_gemini(
    images: List[ExtractedImage],
    gemini_api_key: str,
    gemini_model: str = "gemini-1.5-flash",
) -> List[ExtractedImage]:
    """
    Use Gemini Vision to generate descriptive captions for each extracted image.
    Captions are written into the `caption` field of each ExtractedImage.

    Args:
        images: List of ExtractedImage objects with raw bytes.
        gemini_api_key: Your Gemini API key.
        gemini_model: Gemini model name to use.

    Returns:
        The same list with caption fields populated.
    """
    if not images:
        return images

    try:
        from google import genai
        from google.genai import types as genai_types
        client = genai.Client(api_key=gemini_api_key)
        _use_new_sdk = True
    except (ImportError, AttributeError):
        try:
            import google.generativeai as genai
            genai.configure(api_key=gemini_api_key)
            _use_new_sdk = False
        except ImportError:
            print("[ERROR] google-generativeai not installed. Skipping image captioning.")
            return images

    CAPTION_PROMPT = (
        "You are analyzing an image from an academic/technical PDF document. "
        "Describe this image in detail for a text search system. Include:\n"
        "- What type of content it shows (diagram, graph, table, formula, flowchart, circuit, etc.)\n"
        "- All visible text, labels, axes, legends, or annotations\n"
        "- The main concept or topic the image illustrates\n"
        "- Any numerical values, relationships, or key information visible\n"
        "Be thorough and specific — this description will be used to answer questions about this image."
    )

    captioned = []
    for img in images:
        try:
            img_b64 = base64.b64encode(img.image_bytes).decode("utf-8")
            ext = img.metadata.get("ext", "png")
            mime = f"image/{ext}" if ext in {"png", "jpeg", "jpg", "gif", "webp"} else "image/png"

            if _use_new_sdk:
                from google.genai import types as genai_types
                response = client.models.generate_content(
                    model=gemini_model,
                    contents=[
                        genai_types.Part.from_bytes(data=img.image_bytes, mime_type=mime),
                        CAPTION_PROMPT,
                    ],
                )
                caption = response.text or ""
            else:
                import PIL.Image
                pil_img = PIL.Image.open(io.BytesIO(img.image_bytes))
                model_obj = genai.GenerativeModel(gemini_model)
                response = model_obj.generate_content([CAPTION_PROMPT, pil_img])
                caption = response.text or ""

            img.caption = caption.strip()
            print(f"   [OK] Captioned image on page {img.page_number} ({len(img.caption)} chars)")

        except Exception as e:
            error_str = str(e).lower()
            if "rate" in error_str or "limit" in error_str or "quota" in error_str:
                print(f"   [WARN] Rate limit hit captioning image on page {img.page_number}, skipping.")
            else:
                print(f"   [WARN] Failed to caption image on page {img.page_number}: {e}")
            img.caption = f"[Image on page {img.page_number} - caption unavailable]"

        captioned.append(img)

    return captioned


def images_to_chunks(
    images: List[ExtractedImage],
    subject: str = "",
    filename: str = "",
) -> List[tuple]:
    """
    Convert ExtractedImage objects into (text, metadata) tuples
    ready for embedding and Pinecone upload.

    Only images with non-empty captions are included.

    Args:
        images: List of ExtractedImage objects (captions already populated).
        subject: Subject name for metadata tagging.
        filename: Source PDF filename.

    Returns:
        List of (chunk_text, metadata_dict) tuples.
    """
    chunks = []
    for img in images:
        if not img.caption or img.caption.startswith("[Image on page"):
            continue  # Skip images with no meaningful caption

        text = (
            f"[Image on Page {img.page_number}]\n"
            f"{img.caption}"
        )

        metadata = {
            "content_type": "image",
            "page_number": img.page_number,
            "image_index": img.image_index,
            "subject": subject,
            "filename": filename,
            "has_image": True,
            "image_width": img.width,
            "image_height": img.height,
            "section": f"Image on Page {img.page_number}",
            "topic": "image",
        }

        chunks.append((text, metadata))

    return chunks
